/* CARDIAC//BREACH polish layer — persistence, controls, accessibility and replay UX. */
(()=>{
 const KEY='cardiac-breach-session-v1'; let paused=false, speed=1, lastSave=0;
 const $=id=>document.getElementById(id);
 const toast=(msg)=>{let t=$('cbToast');if(!t){t=document.createElement('div');t.id='cbToast';t.className='cb-toast';document.body.appendChild(t)}t.textContent=msg;t.classList.add('show');clearTimeout(t._x);t._x=setTimeout(()=>t.classList.remove('show'),1800)};
 const save=()=>{try{localStorage.setItem(KEY,JSON.stringify({version:1,scenario:$('scenario')?.value,day,energy,state,cells,agents,events,history,archive,selected,Evolution:{pool:Evolution.pool,generation:Evolution.generation}}));lastSave=Date.now()}catch(e){console.warn('save failed',e)}};
 const load=()=>{try{const raw=localStorage.getItem(KEY);if(!raw)return false;const s=JSON.parse(raw);if(!s||s.version!==1)return false;if(s.scenario)$('scenario').value=s.scenario;day=s.day||0;energy=s.energy??100;Object.assign(state,s.state||{});cells=s.cells||cells;agents=s.agents||[];events=s.events||[];history=s.history||[];archive=s.archive||[];selected=s.selected||0;Evolution.pool=s.Evolution?.pool||[];Evolution.generation=s.Evolution?.generation||0;running=day<MAX_DAYS;renderAgents();renderArchive();renderPopulation();log('SESSION RESTORED — local checkpoint loaded.');draw();updateUI();renderChart();return true}catch(e){console.warn('load failed',e);return false}};
 const addTools=()=>{const host=document.querySelector('.scenario-row');if(!host)return;const box=document.createElement('div');box.className='cb-tools';box.innerHTML='<button class="secondary small" id="pauseRun">PAUSE</button><button class="secondary small" id="saveRun">SAVE</button><button class="secondary small" id="loadRun">LOAD</button><button class="secondary small" id="speedRun">1×</button>';host.appendChild(box);$('pauseRun').onclick=()=>{paused=!paused;$('pauseRun').textContent=paused?'RESUME':'PAUSE';toast(paused?'SIMULATION PAUSED':'SIMULATION RESUMED')};$('saveRun').onclick=()=>{save();toast('CHECKPOINT SAVED')};$('loadRun').onclick=()=>{if(load())toast('CHECKPOINT RESTORED');else toast('NO CHECKPOINT FOUND')};$('speedRun').onclick=()=>{speed=speed===1?2:speed===2?.5:1;$('speedRun').textContent=speed+'×';toast('SIM SPEED '+speed+'×')};};
 const wrapAdvance=()=>{const original=window.advance;if(!original||original.__cbWrapped)return;const wrapped=()=>{if(paused)return;for(let i=0;i<(speed===2?2:1);i++)original();save()};wrapped.__cbWrapped=true;window.advance=wrapped;$('nextDay').onclick=wrapped};
 const shortcuts=()=>document.addEventListener('keydown',e=>{if(e.target.matches('input,select,textarea'))return;const k=e.key.toLowerCase();if(k===' '){e.preventDefault();$('nextDay').click()}else if(k==='n')$('newRun').click();else if(k==='p')$('pauseRun')?.click();else if(k==='s'){$('saveRun')?.click()}else if(k==='f'){document.documentElement.requestFullscreen?.().catch(()=>{})}});
 const autosave=()=>setInterval(()=>{if(running&&Date.now()-lastSave>12000)save()},12000);
 const observe=()=>{const oldReset=window.reset;if(!oldReset||oldReset.__cbWrapped)return;const wrapped=()=>{oldReset();save()};wrapped.__cbWrapped=true;window.reset=wrapped;$('newRun').onclick=wrapped;$('scenario').onchange=wrapped};
 const init=()=>{addTools();wrapAdvance();observe();shortcuts();autosave();if(localStorage.getItem(KEY)){const b=document.createElement('button');b.className='secondary small cb-restore';b.textContent='RESTORE LAST RUN';b.onclick=()=>{if(load()){b.remove();toast('LAST RUN RESTORED')}};document.querySelector('.controls')?.appendChild(b)}window.addEventListener('beforeunload',save);};
 if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(init,0));else setTimeout(init,0);
})();
