const canvas=document.getElementById('tissue'),ctx=canvas.getContext('2d');
const W=14,H=10;let cells=[],selected=0,day=0,energy=84,agents=[],state={viability:72,func:61,inflammation:38,fibrosis:17};
const defs=[{id:'stabilizer',name:'STABILIZER',desc:'Buffers stress and preserves viability.',cost:18},{id:'regenerator',name:'REGENERATOR',desc:'Improves recovery; increases energy demand.',cost:24},{id:'immune',name:'IMMUNE MODULATOR',desc:'Suppresses runaway inflammation.',cost:20},{id:'vascular',name:'VASCULAR SUPPORT',desc:'Improves perfusion and function.',cost:22},{id:'maturation',name:'MATURATION AGENT',desc:'Improves functional maturation.',cost:16}];
const scenarios={ischemia:{damage:.9},inflammation:{damage:.65},fibrosis:{damage:.45},maturation:{damage:.3},arrhythmia:{damage:.55}};
function reset(){day=0;energy=84;agents=[];state={viability:72,func:61,inflammation:38,fibrosis:17};cells=[];for(let y=0;y<H;y++)for(let x=0;x<W;x++){let edge=Math.hypot(x-W/2,y-H/2)/(W/1.8);cells.push({x,y,stress:Math.random()*35+edge*30,damage:Math.random()<.09?65:Math.random()*12,scar:Math.random()*8});}renderAgents();renderLog('RUN INITIALIZED — baseline tissue established.');draw();updateUI()}
function draw(){ctx.clearRect(0,0,canvas.width,canvas.height);let cw=canvas.width/W,ch=canvas.height/H;cells.forEach((c,i)=>{let v=c.damage+c.stress*.55;if(c.scar>35)ctx.fillStyle='#9b78d4';else if(v>75)ctx.fillStyle='#ef6969';else if(v>42)ctx.fillStyle='#f1bd62';else ctx.fillStyle='#d9ff62';ctx.globalAlpha=.45+Math.min(.55,c.damage/130);ctx.fillRect(c.x*cw+2,c.y*ch+2,cw-4,ch-4);if(i===selected){ctx.globalAlpha=1;ctx.strokeStyle='#fff';ctx.lineWidth=2;ctx.strokeRect(c.x*cw+3,c.y*ch+3,cw-6,ch-6)}});ctx.globalAlpha=1}
function updateUI(){for(const k of ['viability','func','inflammation','fibrosis']){document.getElementById(k).textContent=Math.round(state[k])+'%';document.getElementById(k+'Bar').style.width=Math.max(0,Math.min(100,state[k]))+'%'}document.getElementById('energy').textContent=Math.round(energy);document.getElementById('energyBar').style.width=Math.max(0,Math.min(100,energy))+'%';document.getElementById('day').textContent=day;document.getElementById('agentCount').textContent=agents.length+' / 3 deployed';const c=cells[selected];document.getElementById('selected').textContent='REGION '+(selected+1);document.getElementById('inspector').innerHTML=`<b>Region ${selected+1}</b><br><br>Stress: ${Math.round(c.stress)}%<br>Damage: ${Math.round(c.damage)}%<br>Fibrotic signal: ${Math.round(c.scar)}%`}
function renderAgents(){document.getElementById('agentList').innerHTML=defs.map(d=>`<div class="agent"><div><div class="agent-name">${d.name}</div><div class="agent-desc">${d.desc} · ${d.cost} E</div></div><button onclick="deploy('${d.id}')">DEPLOY</button></div>`).join('')}
function deploy(id,name=null){if(agents.length>=3)return renderLog('DEPLOYMENT LIMIT REACHED.',true);let d=defs.find(x=>x.id===id);if(!d||energy<d.cost)return renderLog('INSUFFICIENT ENERGY.',true);energy-=d.cost;agents.push({id,name:name||d.name});renderLog(`${name||d.name} deployed.`);updateUI()}
function advance(){if(day>=20)return;day++;let sc=scenarios[document.getElementById('scenario').value],regen=agents.filter(a=>a.id==='regenerator').length,stab=agents.filter(a=>a.id==='stabilizer').length,imm=agents.filter(a=>a.id==='immune').length,vas=agents.filter(a=>a.id==='vascular').length,mat=agents.filter(a=>a.id==='maturation').length;state.inflammation=Math.max(0,state.inflammation+sc.damage*5-imm*6);state.fibrosis=Math.max(0,state.fibrosis+sc.damage*1.8-stab*1.3);state.viability=Math.max(0,Math.min(100,state.viability-sc.damage*2.5+stab*1.5+regen*1.2+vas*.8));state.func=Math.max(0,Math.min(100,state.func-sc.damage*1.7+regen*.8+vas*2+mat*1.7-imm*.2));energy=Math.max(0,Math.min(100,energy+7-reganCost()));cells.forEach(c=>{c.stress=Math.max(0,c.stress+sc.damage*4-stab*3-vas*1.2+Math.random()*5-2);c.damage=Math.max(0,Math.min(100,c.damage+sc.damage*3+state.inflammation*.025-regen*2));c.scar=Math.max(0,Math.min(100,c.scar+state.inflammation*.015+sc.damage*.5-stab*.5))});renderLog(`DAY ${day}: tissue response updated.`);if(state.viability<35)renderLog('CRITICAL: tissue viability collapsing.',true);if(day===20)renderLog(`RUN COMPLETE — score ${score()}/100.`);draw();updateUI()}
function reganCost(){return agents.reduce((n,a)=>n+(a.id==='regenerator'?3:a.id==='vascular'?2:1),0)}
function score(){return Math.round(state.viability*.4+state.func*.35+(100-state.inflammation)*.1+(100-state.fibrosis)*.15)}
function renderLog(t,warn=false){let el=document.createElement('div');el.className='entry'+(warn?' warn':'');el.innerHTML=`<b>${new Date().toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}</b>${t}`;document.getElementById('log').prepend(el)}
document.getElementById('nextDay').onclick=advance;document.getElementById('newRun').onclick=reset;document.getElementById('scenario').onchange=reset;document.getElementById('deployCustom').onclick=()=>{let n=document.getElementById('agentName').value.trim()||'CUSTOM AGENT';deploy(document.getElementById('agentType').value,n);document.getElementById('agentName').value=''};canvas.onclick=e=>{let r=canvas.getBoundingClientRect();selected=Math.min(cells.length-1,Math.max(0,Math.floor((e.clientY-r.top)/r.height*H)*W+Math.floor((e.clientX-r.left)/r.width*W)));draw();updateUI()};reset();
