/* Contextual visual-asset wiring for CARDIAC//BREACH. */
(()=>{
'use strict';
const $=id=>document.getElementById(id);
const defs={stabilizer:0,regenerator:1,immune:2,vascular:3,maturation:4,electrical:5};
const scenarios=['ischemia','inflammation','fibrosis','maturation','arrhythmia'];
const scenarioLabels={ischemia:['ISCHAEMIA','PERFUSION'],inflammation:['INFLAMMATION','SIGNAL CASCADE'],fibrosis:['FIBROSIS','REMODELING'],maturation:['MATURATION','RECOVERY'],arrhythmia:['ARRHYTHMIA','CONDUCTION']};
function addScenarioStrip(){if($('scenarioArtStrip'))return;const strip=document.createElement('div');strip.id='scenarioArtStrip';strip.className='scenario-art-strip';strip.innerHTML=scenarios.map((s,i)=>`<div class="scenario-art-card" data-scenario="${s}" role="button" tabindex="0"><b>${scenarioLabels[s][0]}</b><span>${scenarioLabels[s][1]}</span></div>`).join('');const anchor=document.querySelector('.scenario-row');anchor?.after(strip);strip.querySelectorAll('.scenario-art-card').forEach(card=>{const pick=()=>{const sel=$('scenario');if(sel){sel.value=card.dataset.scenario;sel.dispatchEvent(new Event('change',{bubbles:true}))}};card.addEventListener('click',pick);card.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();pick()}})});syncScenarioArt()}
function syncScenarioArt(){const s=$('scenario')?.value||'ischemia';document.querySelectorAll('.scenario-art-card').forEach(c=>c.classList.toggle('active',c.dataset.scenario===s))}
function addAgentArt(){const list=$('agentList');if(!list||list.dataset.artReady)return;list.dataset.artReady='1';const obs=new MutationObserver(()=>{list.querySelectorAll('.agent').forEach(row=>{if(row.querySelector('.agent-art'))return;const btn=row.querySelector('button[onclick*="deploy("]');const match=btn?.getAttribute('onclick')?.match(/deploy\('([^']+)'/);const id=match?.[1];if(id===undefined)return;const art=document.createElement('img');art.className='agent-art';art.alt='';art.src='assets/game-art/agent-icons.svg';art.style.objectPosition=`${-defs[id]*44}px 0px`;const content=row.querySelector(':scope > div');if(content){const wrap=document.createElement('div');wrap.className='agent-art-wrap';row.insertBefore(wrap,content);wrap.append(art,content)}})});obs.observe(list,{childList:true,subtree:true});obs.takeRecords();}
function enhanceLegend(){const panel=document.querySelector('.tissue-panel');if(!panel||$('tissueArtKey'))return;const key=document.createElement('div');key.id='tissueArtKey';key.className='tissue-art-key';key.innerHTML='<span><i class="ok"></i>HEALTHY</span><span><i class="stress"></i>STRESSED</span><span><i class="damage"></i>DAMAGED</span><span><i class="scar"></i>FIBROTIC</span><span><i class="recover"></i>RECOVERING</span>';panel.querySelector('.legend')?.after(key)}
function eventArt(){if(!$('finalOverlay'))return;const ov=$('finalOverlay');const mo=new MutationObserver(()=>{const card=ov.querySelector('.decision-card,.why-card,.debrief-card');if(!card||card.querySelector('.event-art'))return;const title=(card.querySelector('h2')?.textContent||'').toLowerCase();let src='assets/game-art/events.svg';const img=document.createElement('img');img.className='event-art';img.src=src;img.alt='';card.insertBefore(img,card.querySelector('h2'))});mo.observe(ov,{childList:true,subtree:true})}
function init(){addScenarioStrip();addAgentArt();enhanceLegend();eventArt();$('scenario')?.addEventListener('change',syncScenarioArt)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(init,260));else setTimeout(init,260);
})();