const canvas=document.getElementById('tissue'),ctx=canvas.getContext('2d');
const W=18,H=12,MAX_DAYS=24,MAX_AGENTS=5;let cells=[],selected=0,day=0,energy=100,agents=[],events=[],history=[],running=false,archive=[];
const state={viability:78,func:64,inflammation:28,fibrosis:12,oxygen:82,arrhythmia:8,metabolic:76};
const scenarios={ischemia:{name:'Ischemic injury',damage:.95,oxygen:-5,inflammation:2,fibrosis:1.2},inflammation:{name:'Inflammatory cascade',damage:.55,oxygen:-1,inflammation:6,fibrosis:1.4},fibrosis:{name:'Progressive fibrosis',damage:.38,oxygen:-1,inflammation:2,fibrosis:4},maturation:{name:'Maturation failure',damage:.25,oxygen:0,inflammation:1,fibrosis:.4},arrhythmia:{name:'Electrical instability',damage:.5,oxygen:-2,inflammation:1,fibrosis:.7}};
const defs=[{id:'stabilizer',name:'STABILIZER',desc:'Reduces stress and secondary injury.',cost:16},{id:'regenerator',name:'REGENERATOR',desc:'Restores viable tissue; consumes extra energy.',cost:22},{id:'immune',name:'IMMUNE MODULATOR',desc:'Limits runaway inflammatory signaling.',cost:18},{id:'vascular',name:'VASCULAR SUPPORT',desc:'Improves oxygen delivery and function.',cost:20},{id:'maturation',name:'MATURATION AGENT',desc:'Improves functional maturation over time.',cost:15},{id:'electrical',name:'ELECTRICAL BUFFER',desc:'Reduces instability and protects conduction.',cost:19}];
const clamp=(v,a=0,b=100)=>Math.max(a,Math.min(b,v));const rand=(a,b)=>a+Math.random()*(b-a);
function neighbors(i){const x=cells[i].x,y=cells[i].y,o=[];for(let dy=-1;dy<=1;dy++)for(let dx=-1;dx<=1;dx++){if(!dx&&!dy)continue;const nx=x+dx,ny=y+dy;if(nx>=0&&nx<W&&ny>=0&&ny<H)o.push(ny*W+nx)}return o}
function reset(){day=0;energy=100;agents=[];events=[];history=[];running=true;Object.assign(state,{viability:78,func:64,inflammation:28,fibrosis:12,oxygen:82,arrhythmia:8,metabolic:76});cells=[];for(let y=0;y<H;y++)for(let x=0;x<W;x++){const edge=Math.hypot(x-(W-1)/2,y-(H-1)/2)/(W*.62),r=Math.random();cells.push({x,y,type:r<.68?'cardiomyocyte':r<.82?'fibroblast':r<.94?'endothelial':'immune',stress:clamp(rand(8,26)+edge*18),damage:clamp(rand(0,12)+(r<.08?35:0)),scar:rand(0,5),oxygen:clamp(88-edge*18+rand(-7,7)),energy:rand(65,92),mature:r<.68?rand(35,72):rand(55,90),alive:true})}log('RUN INITIALIZED — heterogeneous tissue established.');log('Baseline spatial map generated across 216 cells.');renderAgents();renderArchive();draw();updateUI()}
function cellColor(c){if(!c.alive)return'#161d20';if(c.scar>48)return'#9b78d4';const b=c.damage+c.stress*.55+(100-c.oxygen)*.35;return b>78?'#ef6969':b>43?'#f1bd62':'#d9ff62'}
function draw(){ctx.clearRect(0,0,canvas.width,canvas.height);const cw=canvas.width/W,ch=canvas.height/H;cells.forEach((c,i)=>{ctx.fillStyle=cellColor(c);ctx.globalAlpha=.48+Math.min(.5,c.damage/140);ctx.fillRect(c.x*cw+2,c.y*ch+2,cw-4,ch-4);if(c.type==='endothelial'){ctx.strokeStyle='#69b7ff';ctx.lineWidth=1;ctx.strokeRect(c.x*cw+5,c.y*ch+5,cw-10,ch-10)}if(c.type==='immune'){ctx.beginPath();ctx.fillStyle='#f1bd62';ctx.arc(c.x*cw+cw/2,c.y*ch+ch/2,3,0,Math.PI*2);ctx.fill()}if(i===selected){ctx.globalAlpha=1;ctx.strokeStyle='#fff';ctx.lineWidth=2;ctx.strokeRect(c.x*cw+2,c.y*ch+2,cw-4,ch-4)}});ctx.globalAlpha=1}
function updateUI(){['viability','func','inflammation','fibrosis','oxygen','arrhythmia','metabolic'].forEach(k=>{const e=document.getElementById(k);if(e)e.textContent=Math.round(state[k])+'%';const b=document.getElementById(k+'Bar');if(b)b.style.width=clamp(state[k])+'%'});document.getElementById('energy').textContent=Math.round(energy);document.getElementById('energyBar').style.width=energy+'%';document.getElementById('day').textContent=day;document.getElementById('agentCount').textContent=agents.length+' / '+MAX_AGENTS+' deployed';const c=cells[selected];document.getElementById('selected').textContent='REGION '+(selected+1);document.getElementById('inspector').innerHTML=`<b>${c.type.toUpperCase()}</b><br><span class="muted">Region ${selected+1}</span><div class="inspect-grid"><span>Stress <b>${Math.round(c.stress)}%</b></span><span>Damage <b>${Math.round(c.damage)}%</b></span><span>Oxygen <b>${Math.round(c.oxygen)}%</b></span><span>Energy <b>${Math.round(c.energy)}%</b></span><span>Scar <b>${Math.round(c.scar)}%</b></span><span>Maturity <b>${Math.round(c.mature)}%</b></span></div>`;document.getElementById('score').textContent=score()}
function renderAgents(){document.getElementById('agentList').innerHTML=defs.map(d=>`<div class="agent"><div><div class="agent-name">${d.name}</div><div class="agent-desc">${d.desc} · ${d.cost} E</div></div><button ${agents.length>=MAX_AGENTS?'disabled':''} onclick="deploy('${d.id}')">DEPLOY</button></div>`).join('')}
function renderArchive(){const el=document.getElementById('archive');if(!el)return;el.innerHTML=archive.length?archive.map((a,i)=>`<div class="agent"><div><div class="agent-name">${a.name}</div><div class="agent-desc">EVOLVED · LV ${a.level} · FIT ${a.fitness.toFixed(1)}</div></div><button ${agents.length>=MAX_AGENTS?'disabled':''} onclick="deployArchived(${i})">DEPLOY</button></div>`).join(''):'<div class="readout">No archived agents.</div>'}
function deploy(id,name=null){if(agents.length>=MAX_AGENTS)return log('DEPLOYMENT LIMIT REACHED.',true);const d=defs.find(x=>x.id===id);if(!d||energy<d.cost)return log('INSUFFICIENT ENERGY.',true);energy-=d.cost;agents.push({id,name:name||d.name,level:1,uses:0});log(`${name||d.name} deployed at level 1.`);renderAgents();renderArchive();updateUI()}
function deployArchived(i){if(agents.length>=MAX_AGENTS)return log('DEPLOYMENT LIMIT REACHED.',true);const p=archive[i],a=AgentRuntime.fromPolicy(p);if(energy<a.cost)return log('INSUFFICIENT ENERGY FOR EVOLVED AGENT.',true);energy-=a.cost;agents.push(a);log(`${a.name} deployed — evolved policy active.`);renderAgents();renderArchive();updateUI()}
const active=id=>agents.filter(a=>a.id===id).length;
function evolvedEffects(){return agents.filter(a=>a.source==='evolved').reduce((o,a)=>{const e=AgentRuntime.effect(a);Object.keys(o).forEach(k=>o[k]+=e[k]);return o},{stabilize:0,recover:0,immune:0,vascular:0,mature:0,electrical:0})}
function advance(){if(!running)return;if(day>=MAX_DAYS){log('RUN COMPLETE — start a new run to continue.',true);return}const sc=scenarios[document.getElementById('scenario').value];day++;const s=state,stab=active('stabilizer'),regen=active('regenerator'),imm=active('immune'),vas=active('vascular'),mat=active('maturation'),elec=active('electrical'),ev=evolvedEffects();s.oxygen=clamp(s.oxygen+sc.oxygen+vas*3+ev.vascular-stab*.4+rand(-1.5,1.5));s.inflammation=clamp(s.inflammation+sc.inflammation+sc.damage*1.5-imm*4-ev.immune+rand(-1.5,1.5));s.fibrosis=clamp(s.fibrosis+sc.fibrosis+s.inflammation*.018-stab*1.1-regen*.25-ev.stabilize*.15);s.arrhythmia=clamp(s.arrhythmia+(document.getElementById('scenario').value==='arrhythmia'?3.8:sc.damage*.7)-elec*4-vas*.4-ev.electrical+rand(-1,1));s.metabolic=clamp(s.metabolic-sc.damage*2+vas*1.5+stab*.7-regen*1.2+ev.stabilize*.15+rand(-1,1));cells.forEach((c,i)=>{const ns=neighbors(i),local=ns.reduce((a,j)=>a+cells[j].stress,0)/ns.length;c.oxygen=clamp(c.oxygen+(s.oxygen-c.oxygen)*.08+vas*1.1+ev.vascular*.35+rand(-2,2)-sc.damage*2);c.stress=clamp(c.stress+sc.damage*4+(s.inflammation-25)*.035+(100-c.oxygen)*.035-local*.015-stab*2-vas*.5-ev.stabilize*.5+rand(-3,3));c.damage=clamp(c.damage+sc.damage*2.6+c.stress*.018+(100-c.oxygen)*.025-regen*1.6-stab*.8-ev.recover*.4);c.energy=clamp(c.energy+(s.metabolic-c.energy)*.08-c.stress*.03+vas*.5-regen*.3+ev.stabilize*.08);c.scar=clamp(c.scar+sc.fibrosis*.3+s.inflammation*.012-c.damage*.003-stab*.35-ev.stabilize*.04);if(c.type==='cardiomyocyte')c.mature=clamp(c.mature+mat*1.8+regen*.25+ev.mature*.7-(100-c.energy)*.018);if(c.damage>88&&c.oxygen<18)c.alive=false});s.viability=clamp(s.viability-sc.damage*2.2-s.inflammation*.018-(100-s.oxygen)*.025+stab*1.1+regen*1.4-vas*.1+ev.recover*.5+ev.stabilize*.35);s.func=clamp(s.func-sc.damage*1.2-s.fibrosis*.025-s.arrhythmia*.035+regen*1.05+vas*1.7+mat*1.45+elec*.6+ev.recover*.45+ev.vascular*.55+ev.mature*.55+ev.electrical*.25);energy=clamp(energy+8-regCost()-agents.filter(a=>a.source==='evolved').length*1.5);agents.forEach(a=>a.uses++);history.push({day,...s});log(`DAY ${day} — ${sc.name}: oxygen ${Math.round(s.oxygen)}%, inflammation ${Math.round(s.inflammation)}%.`);if(s.viability<35)log('CRITICAL: tissue viability collapsing.',true);if(s.arrhythmia>70)log('CRITICAL: electrical instability spreading.',true);if(day===MAX_DAYS){running=false;log(`RUN COMPLETE — final score ${score()}/100.`)}draw();updateUI();renderChart()}
function regCost(){return agents.reduce((n,a)=>n+(a.id==='regenerator'?4:a.id==='vascular'?2:a.source==='evolved'?2:1),0)}function score(){return Math.round(clamp(state.viability)*.35+clamp(state.func)*.3+(100-state.inflammation)*.1+(100-state.fibrosis)*.1+(100-state.arrhythmia)*.075+state.oxygen*.075)}
function log(text,warn=false){events.unshift({text,warn,time:new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})});const el=document.getElementById('log');if(el)el.innerHTML=events.slice(0,28).map(e=>`<div class="entry ${e.warn?'warn':''}"><b>${e.time}</b>${e.text}</div>`).join('')}
function renderChart(){const cv=document.getElementById('historyChart');if(!cv||history.length<2)return;const x=cv.getContext('2d');x.clearRect(0,0,cv.width,cv.height);['viability','func','oxygen'].forEach((k,n)=>{x.beginPath();history.forEach((p,i)=>{const px=20+i*(cv.width-35)/(MAX_DAYS-1),py=cv.height-15-p[k]/100*(cv.height-30);i?x.lineTo(px,py):x.moveTo(px,py)});x.strokeStyle=['#d9ff62','#75e6d0','#69b7ff'][n];x.lineWidth=2;x.stroke()})}
function renderPopulation(){const el=document.getElementById('population'),lab=document.getElementById('evolutionReadout');if(!Evolution.pool.length){el.innerHTML='<div class="readout">No population yet.</div>';if(lab)lab.textContent='Seed a synthetic population, evaluate it against abstract game outcomes, then evolve the strongest policies.';return}el.innerHTML=Evolution.pool.slice().sort((a,b)=>b.fitness-a.fitness).map(a=>{const bars=Evolution.traits.map(t=>`<i class="${a.traits[t]>.55?'on':''}"></i>`).join('');return `<div class="candidate"><strong>${a.name}</strong><span class="fitness">FIT ${a.fitness.toFixed(1)}</span><br><small>LEVEL ${a.level} · EXP ${a.experience}</small><div class="traitline">${bars}</div><div style="margin-top:7px"><button class="small" onclick="archiveAgent('${a.id}')">ARCHIVE</button></div></div>`}).join('');if(lab){const best=Evolution.pool.slice().sort((a,b)=>b.fitness-a.fitness)[0];lab.innerHTML=`Generation <b>${Evolution.generation}</b><br>Population <b>${Evolution.pool.length}</b><br>Best candidate <b>${best.name}</b><br>Fitness <b>${best.fitness.toFixed(1)}</b><br><br>Archived policies become deployable agents. Their six abstract traits directly modify simulation outcomes.`}document.getElementById('generation').textContent='GEN '+Evolution.generation}
function archiveAgent(id){const a=Evolution.pool.find(x=>x.id===id);if(!a)return;if(!archive.some(x=>x.id===a.id)){archive.push(JSON.parse(JSON.stringify(a)));log(`${a.name} archived as a deployable evolved policy.`)}else log(`${a.name} is already archived.`);renderArchive()}
function exportRun(){const blob=new Blob([JSON.stringify({scenario:document.getElementById('scenario').value,day,state,agents,archive,history,events,evolution:Evolution.summary()},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='cardiac-breach-run.json';a.click();URL.revokeObjectURL(a.href)}
canvas.onclick=e=>{const r=canvas.getBoundingClientRect();selected=Math.min(cells.length-1,Math.max(0,Math.floor((e.clientY-r.top)/r.height*H)*W+Math.floor((e.clientX-r.left)/r.width*W)));draw();updateUI()};document.getElementById('nextDay').onclick=advance;document.getElementById('newRun').onclick=reset;document.getElementById('scenario').onchange=reset;document.getElementById('deployCustom').onclick=()=>{const n=document.getElementById('agentName').value.trim()||'CUSTOM AGENT';deploy(document.getElementById('agentType').value,n);document.getElementById('agentName').value=''};document.getElementById('exportRun').onclick=exportRun;document.getElementById('inspectNeighbors').onclick=()=>{log(`REGION ${selected+1}: ${neighbors(selected).length} neighboring cells sampled.`)};document.getElementById('seedAgents').onclick=()=>{Evolution.seed(8);renderPopulation();log('EVOLUTION LAB: seeded 8 synthetic agent policies.')};document.getElementById('evolveAgents').onclick=()=>{if(!Evolution.pool.length)Evolution.seed(8);const outcome=score();Evolution.evolve(outcome);renderPopulation();log(`EVOLUTION LAB: generation ${Evolution.generation} selected and mutated from fitness ${outcome}.`)};document.getElementById('clearAgents').onclick=()=>{Evolution.pool=[];Evolution.generation=0;renderPopulation();log('EVOLUTION LAB: population cleared.')};reset();renderPopulation();
