/* CARDIAC//BREACH — legacy anatomical viewer compatibility */
(()=>{
'use strict';
const THREE_URL='https://cdn.jsdelivr.net/npm/three@0.128.0/build/three.min.js',GLTF_URL='https://cdn.jsdelivr.net/npm/three@0.128.0/examples/js/loaders/GLTFLoader.js',HEART_URL='https://raw.githubusercontent.com/yihalem123/Human-Organ3D/main/models/heart.glb';
const host=()=>document.getElementById('heart3d');
if(window.CB_IMMERSIVE_UI)return;
const load=u=>new Promise((resolve,reject)=>{const s=document.createElement('script');s.src=u;s.onload=resolve;s.onerror=reject;document.head.appendChild(s);});
async function init(){if(window.CB_IMMERSIVE_UI)return;const el=host();if(!el)return;try{if(!window.THREE)await load(THREE_URL);if(!THREE.GLTFLoader)await load(GLTF_URL);const W=()=>Math.max(300,el.clientWidth||720),H=()=>Math.max(320,el.clientHeight||520),scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(24,W()/H(),.01,100),renderer=new THREE.WebGLRenderer({antialias:true,alpha:true});camera.position.set(0,.15,7.8);renderer.setSize(W(),H(),false);renderer.setPixelRatio(Math.min(devicePixelRatio||1,1.5));el.innerHTML='';el.appendChild(renderer.domElement);scene.add(new THREE.HemisphereLight(0xdce7ef,0x090b0e,1.7));const key=new THREE.DirectionalLight(0xffe1cf,4.2);key.position.set(4,6,7);scene.add(key);const group=new THREE.Group();scene.add(group);const gltf=await new Promise((resolve,reject)=>new THREE.GLTFLoader().load(HEART_URL,resolve,undefined,reject)),model=gltf.scene||gltf.scenes?.[0];group.add(model);const box=new THREE.Box3().setFromObject(model),size=box.getSize(new THREE.Vector3()),center=box.getCenter(new THREE.Vector3());model.position.sub(center);model.scale.multiplyScalar(4.6/(Math.max(size.x,size.y,size.z)||1));camera.position.z=6.5;let dragging=false,lastX=0,lastY=0;renderer.domElement.style.touchAction='none';renderer.domElement.addEventListener('pointerdown',e=>{dragging=true;lastX=e.clientX;lastY=e.clientY});renderer.domElement.addEventListener('pointermove',e=>{if(!dragging)return;group.rotation.y+=(e.clientX-lastX)*.006;group.rotation.x=Math.max(-.55,Math.min(.55,group.rotation.x+(e.clientY-lastY)*.004));lastX=e.clientX;lastY=e.clientY});renderer.domElement.addEventListener('pointerup',()=>dragging=false);renderer.domElement.addEventListener('wheel',e=>{e.preventDefault();camera.position.z=Math.max(3.8,Math.min(12,camera.position.z+e.deltaY*.004))},{passive:false});new ResizeObserver(()=>{const w=W(),h=H();camera.aspect=w/h;camera.updateProjectionMatrix();renderer.setSize(w,h,false)}).observe(el);window.CB_Heart3D={scene,model,group,renderer};const mixer=gltf.animations?.length?new THREE.AnimationMixer(model):null;gltf.animations?.forEach(c=>mixer.clipAction(c).play());const clock=new THREE.Clock();const frame=()=>{requestAnimationFrame(frame);mixer?.update(Math.min(clock.getDelta(),.05));renderer.render(scene,camera)};frame();}catch(e){console.warn('Legacy anatomical viewer unavailable',e)}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
