const {test,expect}=require('@playwright/test');
async function boot(page,viewport){if(viewport)await page.setViewportSize(viewport);await page.goto('/');await page.waitForSelector('#beginnerGuide');await expect(page.locator('#beginnerGuide')).toBeVisible();}
async function hitTest(page,selector){return page.evaluate(selector=>{const target=document.querySelector(selector);if(!target)return null;const r=target.getBoundingClientRect();const x=Math.max(0,Math.min(innerWidth-1,Math.round(r.left+r.width/2))),y=Math.max(0,Math.min(innerHeight-1,Math.round(r.top+r.height/2))),hit=document.elementFromPoint(x,y);return {ok:!!hit&&(hit===target||target.contains(hit)),hitId:hit?.id||'',hitTag:hit?.tagName||''};},selector);}
test.describe('CARDIAC//BREACH visual shell',()=>{
 test('first load has one onboarding layer and no duplicate blockers',async({page})=>{await boot(page);const s=await page.evaluate(()=>({beginner:!!document.querySelector('#beginnerGuide'),quickStart:!!document.querySelector('#cbStart'),oldCoach:!!document.querySelector('#cbCoach'),crisis:document.querySelector('#crisisLayer')?.classList.contains('show')||false,final:document.querySelector('#finalOverlay')?.classList.contains('show')||false,guide:document.documentElement.dataset.beginnerGuide,coord:!!window.CB_UI_COORDINATOR,heart:!!document.querySelector('#heart3d'),v43:document.body.classList.contains('cb-v43')}));expect(s.beginner).toBe(true);expect(s.quickStart).toBe(false);expect(s.oldCoach).toBe(false);expect(s.crisis).toBe(false);expect(s.final).toBe(false);expect(s.guide).toBe('open');expect(s.coord).toBe(true);expect(s.heart).toBe(true);expect(s.v43).toBe(true);});
 test('NEW RUN is actually clickable',async({page})=>{await boot(page,{width:1280,height:720});const g=await page.evaluate(()=>{const a=document.querySelector('.bg-card').getBoundingClientRect(),b=document.querySelector('#newRun').getBoundingClientRect();return !(a.right<=b.left||a.left>=b.right||a.bottom<=b.top||a.top>=b.bottom);});expect(g).toBe(false);expect(await hitTest(page,'#newRun')).toMatchObject({ok:true});await page.getByRole('button',{name:'NEW RUN'}).click();await expect(page.locator('#day')).toHaveText('0');});
 test('STEP 3 advances after a real tissue click',async({page})=>{await boot(page,{width:1280,height:720});for(let i=0;i<3;i++)await page.locator('#bgNext').click();await expect(page.locator('#bgTitle')).toHaveText(/Select tissue/i);await page.locator('#tissue').click({position:{x:450,y:300}});await expect(page.locator('#bgTitle')).toHaveText(/Understand your selection/i);const s=await page.evaluate(()=>({dataset:document.querySelector('#tissue')?.dataset.cbUserSelectedCell,selected:window.CBApp?.selectedCell}));expect(Number.isInteger(Number(s.dataset))).toBe(true);expect(Number.isInteger(s.selected)).toBe(true);});
 test('3D cardiac cockpit renders surface or fallback',async({page})=>{await boot(page,{width:1280,height:720});await page.waitForTimeout(1600);const s=await page.evaluate(()=>({canvas:!!document.querySelector('#heart3d canvas'),fallback:!!document.querySelector('#heart3d .heart3d-fallback'),api:!!window.CB_Heart3D,w:document.querySelector('#heart3d')?.getBoundingClientRect().width,h:document.querySelector('#heart3d')?.getBoundingClientRect().height}));expect(s.w).toBeGreaterThan(400);expect(s.h).toBeGreaterThan(300);expect(s.canvas||s.fallback).toBe(true);});
 test('3D viewport accepts pointer interaction',async({page})=>{await boot(page,{width:1280,height:720});await page.waitForTimeout(1600);const canvas=page.locator('#heart3d canvas');if(await canvas.count()===0){test.skip();return;}await canvas.hover();await page.mouse.down();await page.mouse.move(760,300,{steps:5});await page.mouse.up();await page.mouse.wheel(0,420);await page.mouse.dblclick(760,300);});
 test('mobile onboarding keeps highlighted target reachable',async({page})=>{await boot(page,{width:390,height:844});for(let i=0;i<4;i++){const id=await page.locator('.bg-pulse').getAttribute('id');expect(id).toBeTruthy();expect((await hitTest(page,`#${id}`))?.ok).toBe(true);await page.locator('#bgNext').click();}});
 test('coordinator suppresses recreated overlays while guide is open',async({page})=>{await boot(page);await page.evaluate(()=>{document.querySelector('#crisisLayer')?.classList.add('show');document.querySelector('#finalOverlay')?.classList.add('show');});await page.waitForTimeout(50);const s=await page.evaluate(()=>({crisis:document.querySelector('#crisisLayer')?.classList.contains('show')||false,final:document.querySelector('#finalOverlay')?.classList.contains('show')||false}));expect(s.crisis).toBe(false);expect(s.final).toBe(false);});
 test('closing onboarding restores normal state',async({page})=>{await boot(page);await page.locator('#bgSkip').click();await expect(page.locator('#beginnerGuide')).toHaveCount(0);const s=await page.evaluate(()=>({guide:document.documentElement.dataset.beginnerGuide,body:document.body.classList.contains('beginner-active')}));expect(s.guide).toBe('closed');expect(s.body).toBe(false);});
});
